name: riverpod_widget_annotation
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://furkanacar.dev
repository: https://github.com/AcarFurkan/riverpod_widget_annotation
environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


flutter: